name = "MyProject"
uuid = "cbfa0df6-9a0c-4085-bf33-6267c8bcdb54"
authors = ["Ahan Thakur <ahanthakur.edu@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
